### ISSUE TITLE
Emoji kullanılan yazıların boş içerik olarak düşmesi

### ISSUE THREAD

**Issue by ahmetdereli** [ademilter/s-report#10]
Eğer mobil cihazdan içerik paylaştıysak ve bu içeriğe telefon klavyesinden emoji eklediysek Siteye boş durum olarak düşüyor. Ben twitter ve instagram'da rastladım. Diğerlerinde durum nedir bilmiyorum. Bu durumu nasıl çözebiliriz?
Yazıda sadece başlık ve Text: oluşuyor. Emoji'den itibaren var olan içerik ve ifttt içeriği oluşamıyor.

**Comment by ademilter** [comment]
sorun ifttt tarafında değil wp tarafındaymış.
şununla sorunu çözüyoruz sanırım https://github.com/iamcal/php-emoji
